"""Export functionality for trip planning results to various formats."""

import json
from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime


class TripExporter:
    """Handle exporting trip plans to various formats."""

    @staticmethod
    def export_to_json(trip_plan: str, output_file: Optional[str] = None) -> str:
        """
        Export trip plan to JSON format.
        
        Args:
            trip_plan: Trip plan content (string or dict)
            output_file: Optional output file path
            
        Returns:
            JSON string or file path if saved
        """
        if output_file is None:
            output_file = f"trip_plan_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        try:
            # Try to parse as JSON if it's a string representation of JSON
            if isinstance(trip_plan, str):
                try:
                    data = json.loads(trip_plan)
                except json.JSONDecodeError:
                    data = {"trip_plan": trip_plan}
            else:
                data = trip_plan
            
            with open(output_path, 'w') as f:
                json.dump(data, f, indent=2)
            
            return str(output_path)
        except Exception as e:
            raise Exception(f"Failed to export to JSON: {str(e)}")

    @staticmethod
    def export_to_markdown(trip_plan: str, output_file: Optional[str] = None) -> str:
        """
        Export trip plan to Markdown format.
        
        Args:
            trip_plan: Trip plan content
            output_file: Optional output file path
            
        Returns:
            File path
        """
        if output_file is None:
            output_file = f"trip_plan_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        try:
            content = f"""# Trip Planning Assistant - Generated Plan

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Trip Overview

{trip_plan}

---

*This trip plan was generated by the AI-powered Trip Planning Assistant.*
"""
            
            with open(output_path, 'w') as f:
                f.write(content)
            
            return str(output_path)
        except Exception as e:
            raise Exception(f"Failed to export to Markdown: {str(e)}")

    @staticmethod
    def export_to_csv(data: list, output_file: Optional[str] = None) -> str:
        """
        Export structured data to CSV format.
        
        Args:
            data: List of dictionaries
            output_file: Optional output file path
            
        Returns:
            File path
        """
        if not data or not isinstance(data, list):
            raise ValueError("Data must be a non-empty list")
        
        if output_file is None:
            output_file = f"trip_data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        try:
            import csv
            
            headers = list(data[0].keys())
            
            with open(output_path, 'w', newline='') as f:
                writer = csv.DictWriter(f, fieldnames=headers)
                writer.writeheader()
                writer.writerows(data)
            
            return str(output_path)
        except ImportError:
            raise Exception("CSV export requires 'csv' module (built-in)")
        except Exception as e:
            raise Exception(f"Failed to export to CSV: {str(e)}")

    @staticmethod
    def export_to_html(trip_plan: str, output_file: Optional[str] = None) -> str:
        """
        Export trip plan to HTML format.
        
        Args:
            trip_plan: Trip plan content
            output_file: Optional output file path
            
        Returns:
            File path
        """
        if output_file is None:
            output_file = f"trip_plan_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        try:
            html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trip Plan - {datetime.now().strftime('%Y-%m-%d')}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #3498db;
            margin-top: 30px;
        }}
        h3 {{
            color: #555;
        }}
        .meta {{
            color: #666;
            font-style: italic;
            margin-bottom: 20px;
        }}
        .section {{
            margin-bottom: 20px;
            padding: 15px;
            background-color: #f9f9f9;
            border-left: 4px solid #3498db;
            border-radius: 4px;
        }}
        ul, ol {{
            padding-left: 20px;
        }}
        li {{
            margin-bottom: 8px;
        }}
        .highlight {{
            background-color: #fff3cd;
            padding: 2px 6px;
            border-radius: 3px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🌍 Trip Planning Assistant</h1>
        <div class="meta">
            <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>
        
        <div class="section">
            {trip_plan}
        </div>
        
        <hr>
        <p><em>This trip plan was generated by the AI-powered Trip Planning Assistant.</em></p>
    </div>
</body>
</html>
"""
            
            with open(output_path, 'w') as f:
                f.write(html_content)
            
            return str(output_path)
        except Exception as e:
            raise Exception(f"Failed to export to HTML: {str(e)}")

    @staticmethod
    def create_summary_report(trip_params: Dict[str, Any], 
                            trip_plan: str,
                            output_dir: str = "reports") -> Dict[str, str]:
        """
        Create comprehensive report with all formats.
        
        Args:
            trip_params: Trip planning parameters
            trip_plan: Generated trip plan content
            output_dir: Directory to save reports
            
        Returns:
            Dictionary with file paths for each format
        """
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        
        results = {}
        
        try:
            # Create summary info
            summary = f"""
# Trip Summary

**Destination:** {trip_params.get('destination', 'N/A')}
**Origin:** {trip_params.get('origin', 'N/A')}
**Dates:** {trip_params.get('start_date', 'N/A')} to {trip_params.get('end_date', 'N/A')}
**Budget:** ${trip_params.get('budget', 0):,.2f}
**Travelers:** {trip_params.get('travelers_count', 'N/A')}
**Preferences:** {trip_params.get('preferences', 'N/A')}

## Detailed Plan

{trip_plan}
"""
            
            # Export to multiple formats
            results['markdown'] = TripExporter.export_to_markdown(
                summary,
                f"{output_dir}/trip_plan_{timestamp}.md"
            )
            
            results['html'] = TripExporter.export_to_html(
                summary,
                f"{output_dir}/trip_plan_{timestamp}.html"
            )
            
            results['json'] = TripExporter.export_to_json(
                {
                    'trip_parameters': trip_params,
                    'trip_plan': trip_plan,
                    'generated_at': datetime.now().isoformat()
                },
                f"{output_dir}/trip_plan_{timestamp}.json"
            )
            
            return results
        except Exception as e:
            raise Exception(f"Failed to create summary report: {str(e)}")
